
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job 
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run:  npm install 
      - run : npm run build 
      # - run : npm run deploy 
      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
 


#       steps:
# - uses: actions/checkout@v1

# - run: mkdir -p path/to/artifact

# - run: echo hello > path/to/artifact/world.txt

# - uses: actions/upload-artifact@master
#   with:
#     name: my-artifact
#     path: path/to/artifact

#     You can use the Github Actions upload-artifact and download-artifact to share data between jobs.

# In job1:

# steps:
# - uses: actions/checkout@v1

# - run: mkdir -p path/to/artifact

# - run: echo hello > path/to/artifact/world.txt

# - uses: actions/upload-artifact@master
#   with:
#     name: my-artifact
#     path: path/to/artifact
# And job2:

# steps:
# - uses: actions/checkout@master

# - uses: actions/download-artifact@master
#   with:
#     name: my-artifact
#     path: path/to/artifact

# - run: cat path/to/artifact